### PR TITLE
Improve setup loader performance

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by NicoKiaru** [comment]
Where does all these commits come from :-() ?

**Comment by tischi** [comment]
That was because I first edited the wrong master :-(
I don't know how to clean this up now...
Do you know?
Can I rebase this branch or something?

**Comment by tischi** [comment]
Ah, but if you look at this it is fine:

https://github.com/BIOP/bigdataviewer-bioformats/pull/30/commits/8075f83d3e889e32978847ce439de03575c5ea31

**Comment by NicoKiaru** [comment]
Yes but the last commit contains plenty of unfixed conflicts.

We cannot merge this, it will be a nightmare. You need to merge correctly master before doing your modifications

**Comment by NicoKiaru** [comment]
Look at this : https://github.com/BIOP/bigdataviewer-bioformats/pull/30/commits/eba2d1ded1f0bc7cc2b53a39308305cd56744ef4

**Comment by tischi** [comment]
Strange I thought I fixed them all.
Ok I will scratch this one.

**Pull request closed without merging**
